USE [moneyback]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[f_get_random_name](@IdCustomer INTEGER) RETURNS VARCHAR(8000)
AS
BEGIN

DECLARE @W VARCHAR(8000) = ''

SELECT @W =
MAX( CASE WHEN CN_DICT_CODE = 'surname' THEN CN_VALUE END ) + ' ' +
MAX( CASE WHEN CN_DICT_CODE = 'name' THEN CN_VALUE END ) + ' ' +
MAX( CASE WHEN CN_DICT_CODE = 'patronymic' THEN CN_VALUE END ) 
FROM INVOICE_RESERV.SMASTER.CUSTOMER_NAME_TRN 
WHERE CUSTOMER_ID = @IdCustomer /* FLOOR(RAND()*7865084)+1 */ AND CN_VALUE IS NOT NULL

RETURN ISNULL(@W, 'Гурбанназаров Мухамметмурад Джуманиязович')

END


GO

