USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [A].[APPLICATION](
	[IdObject] [int] NOT NULL,
	[IdParent] [int] NOT NULL,
	[CodeObject] [varchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[RankObject] [int] NOT NULL,
	[NameShort] [nvarchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[NameObject] [nvarchar](1000) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[NoteObject] [nvarchar](4000) COLLATE Cyrillic_General_CS_AI NULL,
 CONSTRAINT [PK_A_APPLICATION] PRIMARY KEY CLUSTERED 
(
	[IdObject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
 CONSTRAINT [UK_APPLICATION] UNIQUE NONCLUSTERED 
(
	[CodeObject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [A].[APPLICATION] ADD  CONSTRAINT [DF_APPLICATION_IdParent]  DEFAULT ((0)) FOR [IdParent]
GO

ALTER TABLE [A].[APPLICATION] ADD  CONSTRAINT [DF_APPLICATION_RankObject]  DEFAULT ((0)) FOR [RankObject]
GO

ALTER TABLE [A].[APPLICATION] ADD  CONSTRAINT [DF_APPLICATION_NameShort]  DEFAULT ('') FOR [NameShort]
GO

ALTER TABLE [A].[APPLICATION]  WITH CHECK ADD  CONSTRAINT [FK_A_APPLICATION] FOREIGN KEY([IdParent])
REFERENCES [A].[APPLICATION] ([IdObject])
GO

ALTER TABLE [A].[APPLICATION] CHECK CONSTRAINT [FK_A_APPLICATION]
GO

