USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [A].[ENTITY_LOCKED](
	[CodeEntity] [varchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[IdObject] [int] NOT NULL,
 CONSTRAINT [PK_ENTITY_LOCKED] PRIMARY KEY CLUSTERED 
(
	[CodeEntity] ASC,
	[IdObject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [A].[ENTITY_LOCKED]  WITH CHECK ADD  CONSTRAINT [FK_ENTITY_LOCKED_ENTITY] FOREIGN KEY([CodeEntity])
REFERENCES [A].[ENTITY] ([CodeObject])
ON UPDATE CASCADE
GO

ALTER TABLE [A].[ENTITY_LOCKED] CHECK CONSTRAINT [FK_ENTITY_LOCKED_ENTITY]
GO

