USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [A].[MESSAGE](
	[IdMessage] [int] NOT NULL,
	[TextMessage] [varchar](4000) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[CodeMessage] [varchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
 CONSTRAINT [Primary_Key_MESSAGE] PRIMARY KEY CLUSTERED 
(
	[IdMessage] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
 CONSTRAINT [Unique_Key_MESSAGE] UNIQUE NONCLUSTERED 
(
	[CodeMessage] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

