USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [A].[PARAMETER](
	[ParameterName] [varchar](200) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[ValueInteger] [int] NOT NULL,
	[ValueString] [varchar](4000) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[ParameterNote] [varchar](8000) COLLATE Cyrillic_General_CS_AI NOT NULL,
 CONSTRAINT [PK_A_PARAMETER] PRIMARY KEY CLUSTERED 
(
	[ParameterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [A].[PARAMETER] ADD  CONSTRAINT [DF_A_PARAMETER_VALUE]  DEFAULT ('') FOR [ValueString]
GO

ALTER TABLE [A].[PARAMETER] ADD  CONSTRAINT [DF_A_PARAMETER_NOTE]  DEFAULT ('') FOR [ParameterNote]
GO

