USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [E].[ACCESS](
	[IdEvent] [bigint] IDENTITY(1,1) NOT NULL,
	[TimeEvent] [datetime] NOT NULL,
	[IdUser] [int] NOT NULL,
	[ApiKey] [varchar](32) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[AddressServer] [varchar](21) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[AddressClient] [varchar](15) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[RefreshToken] [varchar](32) COLLATE Cyrillic_General_CS_AI NOT NULL,
 CONSTRAINT [PK_E_ACCESS] PRIMARY KEY CLUSTERED 
(
	[IdEvent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
 CONSTRAINT [IX_APIKEY] UNIQUE NONCLUSTERED 
(
	[ApiKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
 CONSTRAINT [IX_REFRESHTOKEN] UNIQUE NONCLUSTERED 
(
	[RefreshToken] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [E].[ACCESS] ADD  CONSTRAINT [DF_E_ACCESS_date_event]  DEFAULT (getdate()) FOR [TimeEvent]
GO

ALTER TABLE [E].[ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_USER] FOREIGN KEY([IdUser])
REFERENCES [T].[USER] ([IdUser])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [E].[ACCESS] CHECK CONSTRAINT [FK_ACCESS_USER]
GO

