USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [J].[ROLE_USER](
	[IdUser] [int] NOT NULL,
	[IdRole] [int] NOT NULL,
 CONSTRAINT [PK_ROLE_USER] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC,
	[IdRole] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [J].[ROLE_USER]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_USER_TO_ROLE] FOREIGN KEY([IdRole])
REFERENCES [A].[ROLE] ([IdObject])
ON UPDATE CASCADE
GO

ALTER TABLE [J].[ROLE_USER] CHECK CONSTRAINT [FK_ROLE_USER_TO_ROLE]
GO

ALTER TABLE [J].[ROLE_USER]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_USER_TO_USER] FOREIGN KEY([IdUser])
REFERENCES [T].[USER] ([IdUser])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [J].[ROLE_USER] CHECK CONSTRAINT [FK_ROLE_USER_TO_USER]
GO

