USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [J].[ROLE_ENTITY](
	[IdRole] [int] NOT NULL,
	[IdEntity] [int] NOT NULL,
	[ActionSelect] [tinyint] NOT NULL,
	[ActionInsert] [tinyint] NOT NULL,
	[ActionUpdate] [tinyint] NOT NULL,
	[ActionDelete] [tinyint] NOT NULL,
 CONSTRAINT [PK_J_ROLE_ENTITY] PRIMARY KEY CLUSTERED 
(
	[IdRole] ASC,
	[IdEntity] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [J].[ROLE_ENTITY] ADD  CONSTRAINT [DF_ROLE_ENTITY_ActionSelect]  DEFAULT ((0)) FOR [ActionSelect]
GO

ALTER TABLE [J].[ROLE_ENTITY] ADD  CONSTRAINT [DF_ROLE_ENTITY_ActionInsert]  DEFAULT ((0)) FOR [ActionInsert]
GO

ALTER TABLE [J].[ROLE_ENTITY] ADD  CONSTRAINT [DF_ROLE_ENTITY_ActionUpdate]  DEFAULT ((0)) FOR [ActionUpdate]
GO

ALTER TABLE [J].[ROLE_ENTITY] ADD  CONSTRAINT [DF_ROLE_ENTITY_ActionDelete]  DEFAULT ((0)) FOR [ActionDelete]
GO

ALTER TABLE [J].[ROLE_ENTITY]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_ENTITY_ENTITY] FOREIGN KEY([IdEntity])
REFERENCES [A].[ENTITY] ([IdObject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [J].[ROLE_ENTITY] CHECK CONSTRAINT [FK_ROLE_ENTITY_ENTITY]
GO

ALTER TABLE [J].[ROLE_ENTITY]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_ENTITY_ROLE] FOREIGN KEY([IdRole])
REFERENCES [A].[ROLE] ([IdObject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [J].[ROLE_ENTITY] CHECK CONSTRAINT [FK_ROLE_ENTITY_ROLE]
GO

