USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [T].[CERTIFICATE_HASH](
	[IpAddress] [varchar](50) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[Port] [int] NOT NULL,
	[CertificateHash] [varchar](200) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[TimePoint] [datetime] NOT NULL,
 CONSTRAINT [PK_CERTIFICATE_HASH] PRIMARY KEY CLUSTERED 
(
	[IpAddress] ASC,
	[Port] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [T].[CERTIFICATE_HASH] ADD  CONSTRAINT [DF_CERTIFICATE_HASH_TimePoint]  DEFAULT (getdate()) FOR [TimePoint]
GO

