USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [T].[SESSION](
	[IdSession] [bigint] IDENTITY(1,1) NOT NULL,
	[UserLogin] [varchar](50) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[CodeSession] [varchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[TimeLogin] [datetime] NOT NULL,
 CONSTRAINT [PK_T_SESSION] PRIMARY KEY CLUSTERED 
(
	[IdSession] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
 CONSTRAINT [UK_SESSION] UNIQUE NONCLUSTERED 
(
	[CodeSession] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [T].[SESSION] ADD  CONSTRAINT [DF_SESSION_TIME]  DEFAULT (getdate()) FOR [TimeLogin]
GO

