USE [db_app_server]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [T].[USER](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[UserLogin] [varchar](50) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[PasswordHash] [varchar](1024) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[SaltHash] [varchar](32) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[IdStatus] [int] NOT NULL,
	[IdUnit] [int] NOT NULL,
	[IdPosition] [int] NOT NULL,
	[SurName] [nvarchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[FirstName] [nvarchar](100) COLLATE Cyrillic_General_CS_AI NOT NULL,
	[UserPatronymic] [nvarchar](100) COLLATE Cyrillic_General_CS_AI NULL,
	[UserNote] [nvarchar](4000) COLLATE Cyrillic_General_CS_AI NULL,
 CONSTRAINT [PK_T_USER] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [T].[USER] ADD  CONSTRAINT [DF_T_USER_NOTE]  DEFAULT ('') FOR [UserNote]
GO

ALTER TABLE [T].[USER]  WITH CHECK ADD  CONSTRAINT [FK_T_USER_A_POSITION] FOREIGN KEY([IdPosition])
REFERENCES [A].[POSITION] ([IdObject])
ON UPDATE CASCADE
GO

ALTER TABLE [T].[USER] CHECK CONSTRAINT [FK_T_USER_A_POSITION]
GO

ALTER TABLE [T].[USER]  WITH CHECK ADD  CONSTRAINT [FK_T_USER_A_UNIT] FOREIGN KEY([IdUnit])
REFERENCES [A].[UNIT] ([IdObject])
ON UPDATE CASCADE
GO

ALTER TABLE [T].[USER] CHECK CONSTRAINT [FK_T_USER_A_UNIT]
GO

ALTER TABLE [T].[USER]  WITH CHECK ADD  CONSTRAINT [FK_T_USER_T_STATUS] FOREIGN KEY([IdStatus])
REFERENCES [A].[STATUS] ([IdObject])
ON UPDATE CASCADE
GO

ALTER TABLE [T].[USER] CHECK CONSTRAINT [FK_T_USER_T_STATUS]
GO

