USE [moneyback]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [A].[REQUEST_STATUS](
	[IdRequestStatus] [int] NOT NULL,
	[RequestStatusName] [varchar](50) COLLATE Cyrillic_General_CI_AI NOT NULL,
 CONSTRAINT [PK_A_MONEYBACK_STATUS] PRIMARY KEY CLUSTERED 
(
	[IdRequestStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

