USE [moneyback]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [H].[CLIENT_APPLICATION_VERSION](
	[ClientApplicationVersion] [varchar](50) COLLATE Cyrillic_General_CI_AI NOT NULL,
	[DateProhibition] [datetime] NOT NULL,
	[ProhibitionIsActive] [bit] NOT NULL,
 CONSTRAINT [PK_CLIENT_APPLICATION_VERSION] PRIMARY KEY CLUSTERED 
(
	[ClientApplicationVersion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [H].[CLIENT_APPLICATION_VERSION] ADD  CONSTRAINT [DF_CLIENT_APPLICATION_VERSION_DateProhibition]  DEFAULT (getdate()) FOR [DateProhibition]
GO

ALTER TABLE [H].[CLIENT_APPLICATION_VERSION] ADD  CONSTRAINT [DF_CLIENT_APPLICATION_VERSION_FlagProhibition]  DEFAULT ((1)) FOR [ProhibitionIsActive]
GO

