USE [moneyback]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [H].[MONEY_REQUEST](
	[IdHistory] [int] IDENTITY(1,1) NOT NULL,
	[IdSearch] [int] NOT NULL,
	[IdUser] [int] NOT NULL,
	[DateHistory] [datetime] NOT NULL,
	[IdStatus] [int] NOT NULL,
	[StatementNumber] [varchar](20) COLLATE Cyrillic_General_CI_AI NULL,
	[DateStatement] [varchar](20) COLLATE Cyrillic_General_CI_AI NULL,
	[HistoryNote] [varchar](4000) COLLATE Cyrillic_General_CI_AI NULL,
 CONSTRAINT [PK_H_REQUEST] PRIMARY KEY CLUSTERED 
(
	[IdHistory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [H].[MONEY_REQUEST] ADD  CONSTRAINT [DF_REQUEST_IdUser]  DEFAULT ((0)) FOR [IdUser]
GO

ALTER TABLE [H].[MONEY_REQUEST] ADD  CONSTRAINT [DF_REQUEST_HistoryDate]  DEFAULT (getdate()) FOR [DateHistory]
GO

ALTER TABLE [H].[MONEY_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_MONEY_REQUEST_MONEY_REQUEST] FOREIGN KEY([IdSearch])
REFERENCES [T].[MONEY_REQUEST] ([IdSearch])
ON UPDATE CASCADE
GO

ALTER TABLE [H].[MONEY_REQUEST] CHECK CONSTRAINT [FK_MONEY_REQUEST_MONEY_REQUEST]
GO

ALTER TABLE [H].[MONEY_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_MONEY_REQUEST_REQUEST_STATUS] FOREIGN KEY([IdStatus])
REFERENCES [A].[REQUEST_STATUS] ([IdRequestStatus])
ON UPDATE CASCADE
GO

ALTER TABLE [H].[MONEY_REQUEST] CHECK CONSTRAINT [FK_MONEY_REQUEST_REQUEST_STATUS]
GO

