USE [moneyback]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [T].[MONEY_REQUEST](
	[IdSearch] [int] NOT NULL,
	[IdStatus] [int] NOT NULL,
	[DateCreate] [datetime] NOT NULL,
	[AccountNumber] [int] NOT NULL,
	[IdBank] [int] NOT NULL,
	[BankAccount] [varchar](23) COLLATE Cyrillic_General_CI_AI NULL,
	[CardNumber] [varchar](25) COLLATE Cyrillic_General_CI_AI NULL,
	[BalanceText] [varchar](50) COLLATE Cyrillic_General_CI_AI NULL,
	[BalanceNumeric] [decimal](38, 32) NULL,
	[ClientName] [nvarchar](200) COLLATE Cyrillic_General_CI_AI NULL,
 CONSTRAINT [PK_MONEY_REQUEST] PRIMARY KEY CLUSTERED 
(
	[IdSearch] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [T].[MONEY_REQUEST] ADD  CONSTRAINT [DF_MONEY_REQUEST_IdStatus]  DEFAULT ((0)) FOR [IdStatus]
GO

ALTER TABLE [T].[MONEY_REQUEST] ADD  DEFAULT (getdate()) FOR [DateCreate]
GO

ALTER TABLE [T].[MONEY_REQUEST] ADD  CONSTRAINT [DF_MONEY_REQUEST_IdBank]  DEFAULT ((0)) FOR [IdBank]
GO

ALTER TABLE [T].[MONEY_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_MONEY_REQUEST_BANK] FOREIGN KEY([IdBank])
REFERENCES [A].[BANK] ([IdBank])
ON UPDATE CASCADE
GO

ALTER TABLE [T].[MONEY_REQUEST] CHECK CONSTRAINT [FK_MONEY_REQUEST_BANK]
GO

ALTER TABLE [T].[MONEY_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_MONEY_REQUEST_REQUEST_STATUS] FOREIGN KEY([IdStatus])
REFERENCES [A].[REQUEST_STATUS] ([IdRequestStatus])
GO

ALTER TABLE [T].[MONEY_REQUEST] CHECK CONSTRAINT [FK_MONEY_REQUEST_REQUEST_STATUS]
GO

ALTER TABLE [T].[MONEY_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_MONEY_REQUEST_SEARCH_REQUEST] FOREIGN KEY([IdSearch])
REFERENCES [T].[SEARCH_REQUEST] ([IdSearch])
ON UPDATE CASCADE
GO

ALTER TABLE [T].[MONEY_REQUEST] CHECK CONSTRAINT [FK_MONEY_REQUEST_SEARCH_REQUEST]
GO

